packages:
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.100.9
  "@types/node": ^24.12.2
  "@types/react": ^19.2.14
  react: ^19.2.6
  tsdown: ^0.22.0
  typescript: ^6.0.3
  viem: ^2.48.8
  vitest: ^4.1.5

catalogMode: manual
blockExoticSubdeps: true
minimumReleaseAge: 1440
autoInstallPeers: false

overrides:
  "@types/node": "catalog:"
  "@types/react": "catalog:"
  react: "catalog:"
  typescript: "catalog:"
