// Generated by packages/sdk/scripts/sync-index-dtf-v6-abis.mjs.
// Source: reserve-protocol/reserve-index-dtf@18706fb455b8e6b91250deba795eb791243f6827
// Artifact: out/FolioVersionRegistry.sol/FolioVersionRegistry.json
// Do not edit by hand; run `pnpm abi:index-v6:sync`.
export const folioVersionRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_roleRegistry",
        "type": "address",
        "internalType": "contract IRoleRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deployments",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IFolioDeployer"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deprecateVersion",
    "inputs": [
      {
        "name": "versionHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getImplementationForVersion",
    "inputs": [
      {
        "name": "versionHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "folio",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getLatestVersion",
    "inputs": [],
    "outputs": [
      {
        "name": "versionHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "folioDeployer",
        "type": "address",
        "internalType": "contract IFolioDeployer"
      },
      {
        "name": "deprecated",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isDeprecated",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerVersion",
    "inputs": [
      {
        "name": "folioDeployer",
        "type": "address",
        "internalType": "contract IFolioDeployer"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "roleRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRoleRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "VersionDeprecated",
    "inputs": [
      {
        "name": "versionHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VersionRegistered",
    "inputs": [
      {
        "name": "versionHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "folioDeployer",
        "type": "address",
        "indexed": false,
        "internalType": "contract IFolioDeployer"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "VersionRegistry__AlreadyDeprecated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VersionRegistry__InvalidCaller",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VersionRegistry__InvalidRegistration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VersionRegistry__Unconfigured",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VersionRegistry__ZeroAddress",
    "inputs": []
  }
] as const;
export default folioVersionRegistryAbi;
